### ISSUE TITLE
Bad indentation in example in readme?

### ISSUE THREAD

**Issue by JonJagger** [Entepotenz/keep-github-actions-alive-min-dependencies#10]
The readme file contains this example yml:
```yaml
 name: Github Action with a cronjob trigger
 on:
 schedule:
     - cron: "0 0 * * *"

 jobs:
 cronjob-based-github-action:
     name: Cronjob based github action
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     # - steps
     - uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
```

The indentation of `schedule` and `cronjob-based-github-action` looks wrong here. I think it should be:
```yaml
 name: Github Action with a cronjob trigger
 on:
   schedule:
     - cron: "0 0 * * *"

 jobs:
   cronjob-based-github-action:
     name: Cronjob based github action
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     # - steps
     - uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
```
